name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Set up Environment Variables
      run: |
        echo "POSTGRES_DB_CONNECTION_URL=postgres://postgres:postgres@localhost:5432/test_db" >> $GITHUB_ENV

    - name: Ensure readFile.txt Exists
      run: |
        if [ ! -f ./readFile.txt ]; then
          echo "Creating readFile.txt for tests..."
          echo "This is a test file." > ./readFile.txt
        fi

    - name: Run Tests
      env:
        POSTGRES_DB_CONNECTION_URL: ${{ env.POSTGRES_DB_CONNECTION_URL }}
      run: npm test

    - name: Build Application
      run: npm run build

    - name: Docker Build
      run: docker build -t your-app:latest .
