name: Rollback Pipeline

on:
  workflow_dispatch

jobs:
  rollback:
    runs-on: ubuntu-latest

    steps:
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Rollback Deployment
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@your-ec2-ip << 'EOF'
          cd /path/to/your/app
          git reset --hard HEAD~1
          npm install
          npm run build
          pm2 restart your-app
        EOF
